name: clapper 
base: core22 
grade: stable 
confinement: strict
adopt-info: clapper
compression: lzo
source-code: https://github.com/Rafostar/clapper
website: https://rafostar.github.io/clapper
issues: https://github.com/soumyaDghosh/clapper-snap/issues
license: GPL-3.0

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

lint:
  ignore:
    - classic
    - library

parts:
  meson-deps:
    plugin: nil
    source: https://github.com/ylatuya/meson.git
    source-branch: 'fix-uninstalled'
    source-depth: 1
    override-build: |
      python3 -m pip install .
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages
      rm -rf $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/meson*
      python3 -m pip install --target=$CRAFT_PART_INSTALL/usr .
      mv $CRAFT_PART_INSTALL/usr/meson* $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/
      sed -i "s%^#!/usr/bin/python3$%#!/usr/bin/env python3%g" $CRAFT_PART_INSTALL/usr/bin/meson
    build-packages:
      - python3-pip

  launcher:
    source: .
    plugin: dump
    prime:
      - launcher

  # x264:
  #   plugin: autotools
  #   source: https://salsa.debian.org/multimedia-team/x264.git
  #   source-branch: 'upstream/0.164.3095+gitbaee400'
  #   source-depth: 1
  #   autotools-configure-parameters:
  #     - --prefix=/usr
  #     - --libdir=/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
  #     - --disable-cli
  #     - --enable-shared
  #     - --enable-strip
  #   build-packages:
  #     - nasm
  #   prime:
  #     - -usr/lib/*/pkgconfig
  #     - -usr/include
  #     - -usr/share

  ffmpeg: 
    plugin: autotools
    source: https://git.ffmpeg.org/ffmpeg.git
    source-branch: 'n4.4'
    source-depth: 1
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --disable-everything
      - --enable-gpl
      - --enable-shared
      - --enable-version3
      - --enable-optimizations
      - --enable-runtime-cpudetect
      - --enable-pthreads
      - --enable-protocol=file
      - --enable-decoder=dvvideo,flv,h263,h264,hevc,mjpeg,mpeg2video,mpeg4,mpegvideo,msmpeg4v1,msmpeg4v2,png,tiff,vc1,vp8,vp9,webp,wmv1,wmv2,wmv3,zerocodec
      - --enable-decoder=aac,aac_fixed,aac_latm,ac3,ac3_fixed,ape,dca,dvaudio,eac3,flac,mp3,opus,tak,truehd,tta,wmalossless
      - --enable-demuxer=ape,gif,yuv4mpegpipe
      - --enable-cross-compile
    build-packages:
      - nasm
    prime:
      - -usr/include
      - -usr/share
      - -usr/lib/pkgconfig
      - -usr/lib/*/pkgconfig

  #gtk4:
  #  after: [gstreamer]
  #  plugin: meson
  #  source: https://gitlab.gnome.org/GNOME/gtk.git
  #  source-tag: 4.6.4
  #  meson-parameters:
  #    - --prefix=/usr
  #    - --buildtype=release
  #    - --wrap-mode=nodownload
  #    - -Dwin32-backend=false
  #    - -Dmacos-backend=false
  #    - -Dmedia-ffmpeg=disabled
  #    - -Dprint-cups=disabled
  #    - -Dintrospection=enabled
  #    - -Ddemos=false
  #    - -Dbuild-examples=false
  #    - -Dbuild-tests=false
  #  build-packages:
  #    - libxkbcommon-dev
  #    - libcups2-dev
  #    - libcolord-dev
  #    - libxrandr-dev
  #    - libxcursor-dev
  #    - libisocodes-dev
  #    - libxcomposite-dev
  #    - libxfixes-dev
  #    - libxi-dev
  #    - libxkbfile-dev
  #    - libxml2-utils
  #  override-pull: |
  #    craftctl default
  #    patch -p1 < ${CRAFT_PROJECT_DIR}/patches/gtk4-respect-es-api.patch
  #    patch -p1 < ${CRAFT_PROJECT_DIR}/patches/gtk4-disable-meson-gnome-post-install.patch
  #  stage:
  #    - -usr/bin/wayland-scanner
  #    - -usr/lib/*/libwayland-client.so.0.20.0
  #    - -usr/lib/*/libwayland-server.so.0.20.0
  #  prime:
  #    - -usr/bin/gtk4-builder-tool
  #    - -usr/bin/gtk4-encode-symbolic-svg
  #  organize:
  #    usr/lib/gtk-4.0: usr/lib/$CRAFT_ARCH_TRIPLET/gtk-4.0

  gtuber:
    after: [gstreamer, meson-deps]
    source: https://github.com/Rafostar/gtuber.git
    source-commit: "fb83a368149e6cccc4bce2d3f84cdf4f0e6b3c22"
    source-depth: 1
    plugin: meson
    build-environment:
      - PATH: ${CRAFT_STAGE}/usr/bin:${PATH}
      - PKG_CONFIG_PATH: ${PKG_CONFIG_PATH}:$CRAFT_STAGE/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pkgconfig
    meson-parameters:
      - --prefix=/snap/clapper/current/usr
      - -Dintrospection=disabled
      - -Dvapi=disabled
      - -Dgst-gtuber=enabled
    organize:
      snap/clapper/current: .
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -usr/share

  libdvdcss:
    source: https://code.videolan.org/videolan/libdvdcss.git
    source-tag: 1.4.2
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      - --enable-shared
      - --disable-static
    build-packages:
      - libmpeg2-4-dev
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/lib/*/pkgconfig
      - -usr/share

  # libmpeg2:
  #   source: https://salsa.debian.org/multimedia-team/mpeg2dec.git
  #   source-tag: 'debian/0.5.1-9'
  #   plugin: autotools
  #   autotools-configure-parameters:
  #     - --prefix=/usr
  #     - --libdir=/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
  #     - --enable-shared
  #     - --disable-static
  #   override-pull: |
  #     craftctl default
  #     patch -p1 < ${{CRAFT_PROJECT_DIR}}/patches/libmpeg2-inline.patch
  #     patch -p1 < ${{CRAFT_PROJECT_DIR}}/patches/60_arm-private-symbols.patch
  #     patch -p1 < ${{CRAFT_PROJECT_DIR}}/patches/61_global-symbol-test.patch
  #     patch -p1 < ${{CRAFT_PROJECT_DIR}}/patches/65_arm-test-with-compiler.patch
  #   build-packages:
  #     - libxext-dev
  #   prime:
  #     - -usr/bin/*mpeg2*
  #     - -usr/include
  #     - -usr/lib/pkgconfig
  #     - -usr/lib/*/pkgconfig
  #     - -usr/share

  # liba52:
  #  after: [libmpeg2]
  #  source: http://liba52.sourceforge.net/files/a52dec-0.7.4.tar.gz
  #  plugin: autotools
  #  override-pull: |
  #    craftctl default
  #    patch -p1 < ${CRAFT_PROJECT_DIR}/patches/a52dec-0.7.4-rpath64.patch
  #    patch -p1 < ${CRAFT_PROJECT_DIR}/patches/a52dec-configure-optflags.patch
  #    patch -p1 < ${CRAFT_PROJECT_DIR}/patches/liba52-silence.patch
  #    patch -p1 < ${CRAFT_PROJECT_DIR}/patches/liba52-prefer-pic.patch
  #  autotools-configure-parameters:
  #    - --prefix=/usr
  #    - --libdir=/usr/lib/${CRAFT_ARCH_TRIPLET}
  #    - --enable-shared
  #    - --disable-static
  #  prime:
  #    - -usr/include
  #    - -usr/lib/*/pkgconfig
  #    - -usr/share

  gstreamer:
    after: [ffmpeg, libdvdcss, meson-deps]
    source: https://gitlab.freedesktop.org/gstreamer/gstreamer.git
    source-tag: 1.22.8
    source-depth: 1
    source-submodules: []
    plugin: meson
    build-environment:
      - PATH: ${CRAFT_STAGE}/usr/bin:${PATH}
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - --wrap-mode=nodownload
      - -Dbase=enabled
      - -Dgood=enabled
      - -Dbad=enabled
      - -Dugly=enabled
      - -Dlibav=enabled
      - -Dvaapi=enabled
      - -Dsharp=disabled
      - -Drs=disabled
      - -Dpython=disabled
      - -Ddevtools=disabled
      - -Dges=disabled
      - -Drtsp_server=disabled
      - -Dgst-examples=disabled
      - -Dqt5=disabled
      - -Dtests=disabled
      - -Dexamples=disabled
      - -Dintrospection=enabled
      - -Ddoc=disabled
      - -Dgtk_doc=disabled
      - -Dgpl=enabled
      - -Dgstreamer:benchmarks=disabled
      - -Dgstreamer:gobject-cast-checks=disabled
      - -Dgstreamer:glib-asserts=disabled
      - -Dgstreamer:glib-checks=disabled
      - -Dgstreamer:extra-checks=disabled
      - -Dgst-plugins-base:gobject-cast-checks=disabled
      - -Dgst-plugins-base:glib-asserts=disabled
      - -Dgst-plugins-base:glib-checks=disabled
      - -Dgst-plugins-base:gl_api=opengl,gles2
      - -Dgst-plugins-base:gl_platform=egl,glx
      - -Dgst-plugins-good:gobject-cast-checks=disabled
      - -Dgst-plugins-good:glib-asserts=disabled
      - -Dgst-plugins-good:glib-checks=disabled
      - -Dgst-plugins-good:gtk3=disabled
      - -Dgst-plugins-bad:gobject-cast-checks=disabled
      - -Dgst-plugins-bad:glib-asserts=disabled
      - -Dgst-plugins-bad:glib-checks=disabled
      - -Dgst-plugins-bad:extra-checks=disabled
      - -Dgst-plugins-bad:vulkan=disabled
      - -Dgst-plugins-bad:webrtc=disabled
      - -Dgst-plugins-bad:wasapi=disabled
      - -Dgst-plugins-bad:wasapi2=disabled
      - -Dgst-plugins-bad:winks=disabled
      - -Dgst-plugins-bad:winscreencap=disabled
      - -Dgst-plugins-bad:assrender=enabled
      - -Dgst-plugins-bad:nvcodec=enabled
      - -Dgst-plugins-bad:v4l2codecs=enabled
      - -Dgst-plugins-bad:va=enabled
      - -Dgst-plugins-ugly:gobject-cast-checks=disabled
      - -Dgst-plugins-ugly:glib-asserts=disabled
      - -Dgst-plugins-ugly:glib-checks=disabled
      - -Dgst-plugins-ugly:mpeg2dec=enabled
    override-pull: |
      craftctl default
      echo "Patching Gstreamer libav | total 1 patch"
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/gstreamer/gst-libav-stop-caching-codecs.patch
      sed -i 's|/app/lib|/snap/clapper/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}|' ${CRAFT_PART_SRC}/subprojects/gst-libav/ext/libav/gstav.c

      echo "Patching Gstreamer base | total 3 patches"
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/gstreamer/gst-plugins-base-glupload-filter-formats.patch
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/gstreamer/gst-plugins-base-do-not-use-drm-modifiers-on-desktop.patch
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/gstreamer/gst-plugins-base-autodetect-subtitle-text-encoding.patch

      echo "Patching Gstreamer good | total 4 patches"
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/gstreamer/gst-plugins-good-matroska-fix-attachments-detection.patch
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/gstreamer/gst-plugins-good-matroska-support-seek-nearest-keyframe.patch
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/gstreamer/gst-plugins-good-dashdemux2-improve-initial-representation-selection.patch
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/gstreamer/gst-plugins-good-dashdemux2-play-last-subfragment.patch

      echo "Patching Gstreamer bad | total 4 patches"
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/gstreamer/gst-plugins-bad-dashdemux-sidx-range-download.patch
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/gstreamer/gst-plugins-bad-dashdemux-improve-initial-representation-selection.patch
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/gstreamer/gst-plugins-bad-dvdspu-add-overlay-composition-support.patch
      patch -p1 < ${CRAFT_PROJECT_DIR}/patches/gstreamer/gst-plugins-bad-workaround-playbin2-missing-videometa.patch

      sed -i 's|ISO_CODES_PREFIX |"/snap/clapper/current/gnome-platform/usr"|g' ${CRAFT_PART_SRC}/subprojects/gst-plugins-base/gst-libs/gst/tag/lang.c
    build-packages:
      - liba52-0.7.4-dev
      - libmpeg2-4-dev
      - bison
      - flex
      - gettext
      - libass-dev
      - libffi-dev
      - libgles-dev
      - libgnutls28-dev
      - libgudev-1.0-dev
      - libjpeg-dev
      - libmount-dev
      - libopengl-dev
      - liborc-0.4-dev
      - libpng-dev
      - libpcre3-dev
      - libselinux1-dev
      - libtag1-dev
      - libvpx-dev
      - libwavpack-dev
      - libxrandr-dev
      - libxv-dev
      - yasm
      - zlib1g-dev 
    prime:
      - -usr/libexec
      - -usr/lib/*/pkgconfig
      - -usr/share/man/*
      - -usr/share/gtk-doc/html/*
      - -usr/include

  clapper:
    after: [gstreamer, gtuber, libdvdcss, ffmpeg]
    plugin: meson
    source: https://github.com/Rafostar/clapper.git
    source-tag: '0.5.2'
    source-depth: 1
    build-environment:
      - PATH: ${CRAFT_STAGE}/usr/bin:${PATH}
    meson-parameters:
      - --prefix=/snap/clapper/current/usr
      - -Dc_args="-DHAVE_GST_PATCHES=1"
    build-packages:
      - libgudev-1.0-dev
      - libsass-dev
      - sassc
      - libdv4-dev
      - libdvdread-dev
      - libdvdnav-dev
      - libass-dev
      - libuchardet-dev
    #override-build: |
    #  set -eux
    #  meson $CRAFT_PART_SRC --prefix=/snap/clapper/current/usr -Dc_args='"-DHAVE_GST_PATCHES=1"'
    #  ninja
    #  DESTDIR=$CRAFT_PART_INSTALL
    #  ninja install
    override-pull: |
      craftctl default
      #patch -p1 < ${CRAFT_PROJECT_DIR}/patches/clapper_nvdec.patch
      sed -i -e 's|@GJS@|/snap/clapper/current/gnome-platform/usr/bin/gjs|g' bin/com.github.rafostar.Clapper.in
    organize:
      snap/clapper/current: .
    parse-info: [usr/share/metainfo/com.github.rafostar.Clapper.metainfo.xml]

  deps:
    plugin: nil
    stage-packages:
      - liba52-0.7.4
      - libmpeg2-4
      - libgudev-1.0-0
      - libsass1
      - sassc
      - libdv4
      - libdvdread8
      - libdvdnav4
      - libass9
      - libuchardet0
      - libxv1
      - gstreamer1.0-pipewire
    stage:
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/liba52-0.7.4.so
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libmpeg2.so.0
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libmpeg2.so.0.1.0
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libmpeg2convert.so.0
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libmpeg2convert.so.0.0.0
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libgudev-1.0.so.0
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libgudev-1.0.so.0.3.0
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libsass.so.1
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libsass.so.1.0.0
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libdv.so.4
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libdv.so.4.0.3
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libdvdread.so.8
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libdvdread.so.8.0.0
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libdvdnav.so.4
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libdvdnav.so.4.3.0
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libass.so.9
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libass.so.9.1.3
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libuchardet.so.0
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libuchardet.so.0.0.7
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libXv.so.1
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libXv.so.1.0.0
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gstreamer-1.0/libgstpipewire.so

slots:
  clapper-mpris:
    interface: mpris
    name: Clapper
  clapper:
    interface: dbus
    bus: session
    name: com.github.rafostar.Clapper

apps:
  clapper:
    command: usr/bin/com.github.rafostar.Clapper
    command-chain:
      - launcher
    desktop: usr/share/applications/com.github.rafostar.Clapper.desktop
    environment:
      GI_TYPELIB_PATH: $SNAP/gnome-platform/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gjs/girepository-1.0:${GI_TYPELIB_PATH}
      LD_LIBRARY_PATH: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:${LD_LIBRARY_PATH}
      GDK_DEBUG: portals
    common-id: com.github.rafostar.Clapper
    extensions: [ gnome ]
    plugs:
      - home
      - audio-playback
      - mount-observe
      - screen-inhibit-control
      - network
      - network-status
    slots:
      - clapper-mpris
      - clapper
