name: clapper # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.5.2' # just for humans typically '1.2+git' or '1.3.2'
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: com.github.rafostar.Clapper.svg
adopt-info: clapper
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
parts:
  gtk4:
    after: [gstreamer]
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/gtk.git
    source-tag: 4.6.4
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - --wrap-mode=nodownload
      - -Dwin32-backend=false
      - -Dmacos-backend=false
      - -Dmedia-ffmpeg=disabled
      - -Dprint-cups=disabled
      - -Dintrospection=enabled
      - -Ddemos=false
      - -Dbuild-examples=false
      - -Dbuild-tests=false
    build-packages:
      - libxkbcommon-dev
      - libcups2-dev
      - libcolord-dev
      - libxrandr-dev
      - libxcursor-dev
      - libisocodes-dev
      - libxcomposite-dev
      - libxdamage-dev
      - libxfixes-dev
      - libxi-dev
      - libxkbfile-dev
      - libxml2-utils
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/patches/gtk4-respect-es-api.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/gtk4-disable-meson-gnome-post-install.patch
    stage:
      - -usr/bin/wayland-scanner
      - -usr/lib/*/libwayland-client.so.0.20.0
      - -usr/lib/*/libwayland-server.so.0.20.0
    prime:
      - -usr/bin/gtk4-builder-tool
      - -usr/bin/gtk4-encode-symbolic-svg
    organize:
      usr/lib/gtk-4.0: usr/lib/$CRAFT_ARCH_TRIPLET/gtk-4.0    
  gtuber:
    after: [gstreamer]
    source: https://github.com/Rafostar/gtuber.git
    plugin: meson
    build-environment:
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/lib/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
    meson-parameters:
      - --prefix=/usr
      - -Dintrospection=disabled
      - -Dvapi=disabled
      - -Dgst-gtuber=enabled      
  libdvdcss:
    after: [libmpeg2]
    source: https://code.videolan.org/videolan/libdvdcss.git
    source-tag: 1.4.2
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-shared
      - --disable-static    
  libmpeg2:
    source: http://libmpeg2.sourceforge.net/files/libmpeg2-0.5.1.tar.gz
    plugin: autotools
    build-environment:
     # - LDFLAGS: $CRAFT_PART_STAGE/usr/include:$LDFLAGS
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-shared
      - --disable-static
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/patches/libmpeg2-inline.patch
    build-packages:
      - ffmpeg
      - libxext-dev
    prime:
      - -usr/bin/*mpeg2*
  liba52:
    after: [libmpeg2]
    source: http://liba52.sourceforge.net/files/a52dec-0.7.4.tar.gz
    plugin: autotools
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/patches/a52dec-0.7.4-rpath64.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/a52dec-configure-optflags.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/liba52-silence.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/liba52-prefer-pic.patch
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-shared
      - --disable-static
    prime:
      - -usr/bin/*a52*
  gstreamer:
    after: [libmpeg2]
    source: https://gitlab.freedesktop.org/gstreamer/gstreamer.git
    source-tag: 1.20.2
    source-submodules: []
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - --wrap-mode=nodownload
      - -Dbase=enabled
      - -Dgood=enabled
      - -Dbad=enabled
      - -Dugly=enabled
      - -Dlibav=enabled
      - -Dvaapi=enabled
      - -Dsharp=disabled
      - -Drs=disabled
      - -Dpython=disabled
      - -Ddevtools=disabled
      - -Dges=disabled
      - -Drtsp_server=disabled
      - -Dgst-examples=disabled
      - -Dqt5=disabled
      - -Dtests=disabled
      - -Dexamples=disabled
      - -Dintrospection=enabled
      - -Ddoc=disabled
      - -Dgtk_doc=disabled
      - -Dgpl=enabled
      - -Dgstreamer:benchmarks=disabled
      - -Dgstreamer:gobject-cast-checks=disabled
      - -Dgstreamer:glib-asserts=disabled
      - -Dgstreamer:glib-checks=disabled
      - -Dgstreamer:extra-checks=disabled
      - -Dgst-plugins-base:gobject-cast-checks=disabled
      - -Dgst-plugins-base:glib-asserts=disabled
      - -Dgst-plugins-base:glib-checks=disabled
      - -Dgst-plugins-base:gl_api=opengl,gles2
      - -Dgst-plugins-base:gl_platform=egl,glx
      - -Dgst-plugins-good:gobject-cast-checks=disabled
      - -Dgst-plugins-good:glib-asserts=disabled
      - -Dgst-plugins-good:glib-checks=disabled
      - -Dgst-plugins-good:gtk3=disabled
      - -Dgst-plugins-bad:gobject-cast-checks=disabled
      - -Dgst-plugins-bad:glib-asserts=disabled
      - -Dgst-plugins-bad:glib-checks=disabled
      - -Dgst-plugins-bad:extra-checks=disabled
      - -Dgst-plugins-bad:vulkan=disabled
      - -Dgst-plugins-bad:webrtc=disabled
      - -Dgst-plugins-bad:wasapi=disabled
      - -Dgst-plugins-bad:wasapi2=disabled
      - -Dgst-plugins-bad:winks=disabled
      - -Dgst-plugins-bad:winscreencap=disabled
      - -Dgst-plugins-bad:assrender=enabled
      - -Dgst-plugins-bad:nvcodec=enabled
      - -Dgst-plugins-bad:v4l2codecs=enabled
      - -Dgst-plugins-bad:va=enabled
      - -Dgst-plugins-ugly:gobject-cast-checks=disabled
      - -Dgst-plugins-ugly:glib-asserts=disabled
      - -Dgst-plugins-ugly:glib-checks=disabled
      - -Dgst-plugins-ugly:mpeg2dec=enabled
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/patches/gst-libav-stop-caching-codecs.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/gst-plugins-base-do-not-set-backbuffer.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/gst-plugins-base-glupload-filter-formats.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/gst-plugins-base-do-not-use-drm-modifiers-on-desktop.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/gst-plugins-base-autodetect-subtitle-text-encoding.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/gst-plugins-good-matroska-fix-attachments-detection.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/gst-plugins-good-matroska-support-seek-nearest-keyframe.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/gst-plugins-bad-dashdemux-sidx-range-download.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/gst-plugins-bad-dashdemux-improve-initial-representation-selection.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/gst-plugins-bad-mpdparser-fix-missing-uri-query.patch
      patch -p1 < $CRAFT_PROJECT_DIR/patches/gst-plugins-bad-workaround-playbin2-missing-videometa.patch
    build-packages:
      - bison
      - flex
      - gettext
      - libgnutls28-dev
      - liborc-0.4-dev
      - libpulse-dev
      - libva-dev
      - libwayland-dev
      - libxrandr-dev
      - yasm
      - libxv-dev
      - libtag1-dev
      - libwavpack-dev
      - ffmpeg
      - python3-pip
      - libgirepository1.0-dev
      - libopengl-dev
      - libgles-dev
      - libgudev-1.0-dev
      - libass-dev
      - libmpeg2-4-dev
      - liba52-0.7.4-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libffi-dev
      - libpcre3-dev
      - zlib1g-dev
      - libmount-dev
      - libselinux1-dev
      - libjpeg-dev
      - libpng-dev
      - libvpx-dev
      - libx264-dev
    stage-packages:
      - liborc-0.4-0
      - libpulse0
    prime:
      - -usr/share/man/*
      - -usr/share/gtk-doc/html/*
      - -usr/include/gst*
  clapper:
    after: [ libmpeg2, gstreamer, gtuber, libdvdcss, liba52, gtk4 ]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/Rafostar/clapper.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    build-environment:
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/lib/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH} 
    meson-parameters:
      - --prefix=/snap/clapper/current/usr
      - -Dc_args="-DHAVE_GST_PATCHES=1"
    build-packages:
      - ffmpeg
      - libgudev-1.0-dev
      - libsass-dev
      - sassc
      - libdv4-dev
      - libdvdread-dev
      - libdvdnav-dev
      - libass-dev
      - libuchardet-dev
    stage-packages:
      - libgudev-1.0-0
      - libsass1
      - sassc
      - libdv4
      - libdvdread8
      - libdvdnav4
      - libass9
      - uchardet
    #override-build: |
    #  set -eux
    #  meson $CRAFT_PART_SRC --prefix=/snap/clapper/current/usr -Dc_args='"-DHAVE_GST_PATCHES=1"'
    #  ninja
    #  DESTDIR=$CRAFT_PART_INSTALL
    #  ninja install
    #override-prime: |
    #  craftctl default
    #  ln -s $CRAFT_PRIME/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstpipewire.so $CRAFT_PRIME/usr/lib/gstreamer-1.0/
    organize:
      snap/clapper/current: .
    parse-info: [ usr/share/metainfo/com.github.rafostar.Clapper.metainfo.xml ]
      
slots:
  clapper-mpris:
    interface: mpris
    name: Clapper
  clapper:
    interface: dbus
    bus: session
    name: com.github.rafostar.Clapper
  gnome-shell:
    interface: dbus
    bus: session
    name: org.gnome.Shell
  gtk-daemon:
    interface: dbus
    bus: session
    name: org.gtk.vfs.Daemon
apps:
  clapper:
    command: usr/bin/com.github.rafostar.Clapper
    desktop: usr/share/applications/com.github.rafostar.Clapper.desktop
    environment:
      GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/gstreamer-1.0
    common-id: com.github.rafostar.Clapper
    extensions: [ gnome ]
    plugs:
      - home
      - audio-playback
      - media-control
    slots:
      - clapper-mpris
      - clapper
      - gnome-shell
      - gtk-daemon
