name: Build Clapper
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
permissions:
  id-token: write
  contents: read
jobs:
  deploy-snap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Build Clapper Snap
        uses: snapcore/action-build@v1
        id: snapcraft-build
        env:
          SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: 1
        with:
          snapcraft-args: "--verbosity debug"
      - uses: actions/upload-artifact@v3
        with:
          name: clapper-snap
          path: ${{ steps.snapcraft-build.outputs.snap }}    
